//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercury.Web.Application.Workflow.UserInteractions {
    
    
    public partial class SendCorrespondence {
        
        /// <summary>
        /// TelerikAjaxManagerProxy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadAjaxManagerProxy TelerikAjaxManagerProxy;
        
        /// <summary>
        /// EntityInfoSendCorrespondenceSplitter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadSplitter EntityInfoSendCorrespondenceSplitter;
        
        /// <summary>
        /// EntityInfoPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadPane EntityInfoPane;
        
        /// <summary>
        /// EntityInfoSlidingZone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadSlidingZone EntityInfoSlidingZone;
        
        /// <summary>
        /// EntityInfoDemographics control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadSlidingPane EntityInfoDemographics;
        
        /// <summary>
        /// MemberDemographicsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mercury.Web.Application.MemberProfile.MemberProfileDemographics MemberDemographicsControl;
        
        /// <summary>
        /// ProviderDemographicsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mercury.Web.Application.Controls.ProviderDemographics ProviderDemographicsControl;
        
        /// <summary>
        /// EntityInfoSendCorrespondenceHistory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadSlidingPane EntityInfoSendCorrespondenceHistory;
        
        /// <summary>
        /// EntityDocumentHistoryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mercury.Web.Application.Controls.EntityDocumentHistory EntityDocumentHistoryControl;
        
        /// <summary>
        /// EntityNoteHistorySlidingPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadSlidingPane EntityNoteHistorySlidingPane;
        
        /// <summary>
        /// EntityNoteHistoryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mercury.Web.Application.Controls.EntityNoteHistory EntityNoteHistoryControl;
        
        /// <summary>
        /// EntitySendCorrespondencePane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadPane EntitySendCorrespondencePane;
        
        /// <summary>
        /// EntitySendCorrespondenceControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mercury.Web.Application.Controls.EntitySendCorrespondence EntitySendCorrespondenceControl;
        
        /// <summary>
        /// RadScriptBlock1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadScriptBlock RadScriptBlock1;
    }
}
