-- DBO.[MEMBERCASEPROBLEMCAREPLANINTERVENTION] (BEGIN) 

/* 
IF EXISTS (SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE (TABLE_NAME = 'MemberCaseProblemCarePlanIntervention')  AND (TABLE_SCHEMA = 'dbo'))
  DROP TABLE dbo.[MemberCaseProblemCarePlanIntervention]
GO 
*/ 


